<?php

$mapData = $this->displayMap($this->map,$this->elementList,1);

$this->headStyle()->appendStyle($mapData['style']);
$this->headStyle()->appendStyle($mapData['style'],array('media'=>'print'));


$this->headScript()->appendScript($mapData['script']);
 
 

   
?>




<!-- Render the hex map inside of a div block -->
<div class="well">
        <div class="row">
    <div class="span3 offset9">
        <div class="btn-group">
        <a class="btn " href="<?=$this->url(array('controller' => 'manage', 'action' => 'createrandomelement', 'density' => 45));?>">
            <i class="icon-random "></i> Création Aléatoire
        </a>
        
   
        <a class="btn btn-danger" href="<?=$this->url(array('controller' => 'manage', 'action' => 'deleteallelements', 'mapid' => $this->map->id));?>">
            <i class="icon-trash icon-white"></i> Vider la carte
        </a>
        </div>
        
    </div>
    
</div>
        
            <div id='hexmap' class='hexmap'>
         <?php echo $mapData['maphtml']; ?>
            </div>

        
    </div>

   

<div id="adminTable">
    
  
        <table class="table table-striped table-bordered table-condensed">
            <thead>
                <tr>
                    <th>id</th>
                    <th>Image</th>
                    <th>Nom</th>
                    <th>Type</th>
                    <th>Ressources</th>
                    <th>Population</th>
                    <th>Tech</th>
                    <th>Defense</th>
                    <th>Coordonnées</th>
                    <th>actif</th>
                    <th>actions</th>

                </tr>

            </thead>




        <?php

        if(count($this->elementList))
            foreach($this->elementList as $element){



            ?>
            <tr>
                <td><?echo $element->id;?></td>
                <td><img src="<?echo Model_DbTable_Element::IMAGEPATH.$element->image;?>"/></td>
                <td><?echo $element->name;?></td>
                <td> <? echo $element->type?>
                <td><?echo $element->ressources;?></td>
                <td><?echo $element->population;?></td>
                <td><?echo $element->tech;?></td>
                <td><?echo $element->defences;?></td>
                <td>X:<?echo $element->Xcoord;?>-Y:<?echo $element->Ycoord;?></td>
                <td>
                    <a class="active<?echo $element->active; ?> <?=($element->active)?"badge badge-success":"badge badge-important"; ?>" href="/manage/toggleelement/id/<?echo $element->id;?>">
                    <?=($element->active)?"<i class='icon-ok icon-white'></i>":"<i class='icon-remove icon-white'></i>"?>
                    </a>   
                </td>
                <td>
                     <div class="btn-group">
                    <a class="btn btn-danger" href="/manage/deleteelement/id/<?echo $element->id;?>">delete</a>
                   
 
               
 <?=$this->ajaxLink("<i class='icon-edit'></i>Modifier",
                        $this->url(array('controller' => 'manage', 'action' => 'elementshow','ycoord'=>$element->Ycoord, 'xcoord'=>$element->Xcoord, 'mapid'=>$element->mapid)) ,
                            array('update' => '#modal .modal-body',
                            'class' => 'btn',
                            'beforeSend' => "$('#elementdetailcontent').hide('slow');$('#elementdetail').hide('slow');",
                            'complete' => "showModal()",
                          ));?>
                     </div>

                </td>

            </tr>

            <?php
            }

        ?>



        </table>
</div>

<div class="clear:both"></div>

  
