<?php 
$this->layout()->title = $this->map->name;


//recuperation des données de carte

$mapData = $this->displayMap($this->map,$this->elementList,1);

// ajouts des elements css dynamique et js dynamique
$this->headStyle()->appendStyle($mapData['style']);
$this->headScript()->appendScript($mapData['script']);
?>       



    

    

     <!-- Render the hex map inside of a div block -->
   <div class="well">
        
        <div id='hexmap' class='hexmap'>
         <?php echo $mapData['maphtml']; ?>
        </div>
        <div style="clear:both;"></div>
   </div>

   
    