<?php 

// mise en place de la toolbar : 
$this->layout()->toolbar = $this->toolbar;

$this->layout()->title = $this->map->name;


//recuperation des données de carte
$mapData = $this->displayMap($this->map,$this->elements,0.5);

// ajouts des elements css dynamique et js dynamique
$this->headStyle()->appendStyle($mapData['style']);
$this->headScript()->appendScript($mapData['script']);
?>       

    
   

     <!-- Render the hex map inside of a div block -->
    <div id='hexmap' class='hexmap' onclick='handle_map_click(event);'>
        <?php echo $mapData['maphtml']; ?>
        <img id='highlight' class='hex' src='/images/map/hex-highlight.png' style='zindex:100;'>
    </div>

   
    