<?php echo $this->doctype() ?>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php 
    echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8'); 
    
        
    ZendX_JQuery::enableView($this);

    echo  $this->jQuery()
                ->setVersion('1.7.2')
                ->setUiVersion('1.8.21')
                ->enable()
                ->uiEnable();
                
           // twitter bootstrap
    $this->headScript()->prependFile('/css/bootstrap/js/bootstrap.min.js');
    
    
    
     $jScript=<<<EOD
   
            function showModal(){
   
            $('#modal .modal-title').html($('#modal .modal-title-hidden').html());
            $('#modal').modal('show');
}
   
EOD;
        $this->headScript()->appendScript($jScript);
    
    ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
</head>
<body>
    
    <?php echo $this->layout()->toolbar;?>
    
  
    
        
    
    <div class="container">
          
    <header class="jumbotron subhead" id="overview">
  <h1><?php echo $this->layout()->subtitle;?></h1>
  <p class="lead"><?php echo $this->layout()->summary;?></p>
  <div class="subnav">
    <?php echo $this->layout()->subnav;?>
  </div>
</header>
        
    <?php echo $this->layout()->content ?>
     </div>
    
    
    <div class="modal hide" id="modal">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3 class="modal-title">&nbsp;</h3>
        </div>
        <div class="modal-body">
            
        </div>
        <div class="modal-footer">
            <!--<a href="#" class="btn" data-dismiss="modal">Close</a>-->
            
        </div>
    </div>
    
</body>
</html>