<?php

$mapData = $this->displayMap($this->map,$this->elementList,1);

$this->headStyle()->appendStyle($mapData['style']);
$this->headStyle()->appendStyle($mapData['style'],array('media'=>'print'));


$this->headScript()->appendScript($mapData['script']);
 
 

   
?>

<div class="modal hide" id="modal">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Modal header</h3>
        </div>
        <div class="modal-body" id="elementdetailcontent">
            
        </div>
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">Close</a>
            <a href="#" class="btn btn-primary">Save changes</a>
        </div>
</div>


<!-- Render the hex map inside of a div block -->
<div class="well">
        <div class="row">
    <div class="span3 offset9">
        <a class="btn btn-primary" href="<?=$this->url(array('controller' => 'admin', 'action' => 'createrandomelement', 'density' => 45));?>">
            <i class="icon-random icon-white"></i>Création Aléatoire
        </a>
        
   
        <a class="btn btn-danger" href="<?=$this->url(array('controller' => 'admin', 'action' => 'deleteallelements', 'mapid' => $this->map->id));?>">
            <i class="icon-trash icon-white"></i>Vider la carte
        </a>
        
    </div>
    
</div>
        
            <div id='hexmap' class='hexmap'>
         <?php echo $mapData['maphtml']; ?>
            </div>

        
    </div>

   

<div id="adminTable">
    
  
        <table class="table table-striped table-bordered table-condensed">
            <thead>
                <tr>
                    <th>id</th>
                    <th>Image</th>
                    <th>Nom</th>
                    <th>Type</th>
                    <th>Ressources</th>
                    <th>Population</th>
                    <th>Tech</th>
                    <th>Defense</th>
                    <th>Coordonnées</th>
                    <th>actif</th>
                    <th>actions</th>

                </tr>

            </thead>




        <?php

        if(count($this->elementList))
            foreach($this->elementList as $element){



            ?>
            <tr>
                <td><?echo $element->id;?></td>
                <td><img src="<?echo Model_DbTable_Element::IMAGEPATH.$element->image;?>"/></td>
                <td><?echo $element->name;?></td>
                <td> <? echo $element->type?>
                <td><?echo $element->ressources;?></td>
                <td><?echo $element->population;?></td>
                <td><?echo $element->tech;?></td>
                <td><?echo $element->defences;?></td>
                <td>X:<?echo $element->Xcoord;?>-Y:<?echo $element->Ycoord;?></td>
                <td>
                    <a class="active<?echo $element->active; ?>" href="/admin/switchactivation/mapid/<?echo $element->id;?>">
                    <?=($element->active)?"desactiver":"activer"?>
                    </a>    
                </td>
                <td>
                    <a class="delete" href="/admin/deleteelement/id/<?echo $element->id;?>">delete</a>
                    <a class="edit" href="/admin/editelement/id/<?echo $element->id;?>">edit</a>

                </td>

            </tr>

            <?php
            }

        ?>



        </table>
</div>

<div class="clear:both"></div>

  
