<?php

 

?>


<div id="adminTable">
    
    <?=$this->ajaxLink("<i class='icon-plus icon-white'></i>Ajouter",
                  $this->url(array('controller' => 'admin', 'action' => 'adduser')) ,
                    array('update' => '#modal .modal-body',
                            'class' => 'btn btn-success',
                            'beforeSend' => "$('#elementdetailcontent').hide('slow');$('#elementdetail').hide('slow');",
                        'complete' => "showModal();",
                          ));?>
   
        <table class="table table-striped table-bordered table-condensed">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                    <th>Email</th>
                    <th>Actif</th>
                    <th>Admin</th>
                    <th>Action</th>
                </tr>

            </thead>




        <?php

        if(count($this->list))
            foreach($this->list as $user){



            ?>
            <tr>
                <td><?echo $user->id;?></td>
                <td><?echo $user->username;?></td>
                <td> <? echo $user->email?>
                <td>
                    <a class="active<?echo $user->active; ?> <?=($user->active)?"badge badge-success":"badge badge-important"; ?>" href="/admin/switchuseractivation/id/<?echo $user->id;?>">
                    <?=($user->active)?"<i class='icon-ok icon-white'></i>":"<i class='icon-remove icon-white'></i>"?>
                    </a>    
                </td>
                <td>
                    <?=($user->role)?"Admin":"-"?>
                </td>
                <td>
                    <a class="btn btn-danger" href="/admin/deleteuser/id/<?echo $user->id;?>"><i class='icon-trash icon-white'></i>delete</a>
                     <?=$this->ajaxLink("<i class='icon-edit'></i>Modifier",
                        $this->url(array('controller' => 'admin', 'action' => 'adduser', 'id'=>$user->id)) ,
                            array('update' => '#elementdetailcontent',
                            'class' => 'btn',
                            'beforeSend' => "$('#elementdetailcontent').hide('slow');$('#elementdetail').hide('slow');",
                            'complete' => "$('#elementdetail').show('slow');$('#elementdetailcontent').show('fast');",
                          ));?>
                </td>

            </tr>

            <?php
            }

        ?>



        </table>
</div>

<div class="clear:both"></div>
