<?php

 

?>


<div id="adminTable">
    
    <?=$this->ajaxLink("<i class='icon-plus icon-white'></i>Ajouter",
                  $this->url(array('controller' => 'admin', 'action' => 'adduser')) ,
                    array('update' => '#modal .modal-body',
                            'class' => 'btn btn-success',
                            'beforeSend' => "$('#elementdetailcontent').hide('slow');$('#elementdetail').hide('slow');",
                        'complete' => "showModal();",
                          ));?>
   
        <table class="table table-striped table-bordered table-condensed">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                    <th>Email</th>
                    <th>Actif</th>
                    <th>Admin</th>
                    <th>Action</th>
                </tr>

            </thead>




        <?php

        if(count($this->list))
            foreach($this->list as $user){



            ?>
            <tr>
                <td><?echo $user->id;?></td>
                <td><?echo $user->username;?></td>
                <td> <? echo $user->email?>
                <td>
                    <a class="active<?echo $user->active; ?> <?=($user->active)?"badge badge-success":"badge badge-important"; ?>" 
                        href="<?= $this->url(array('controller'=>'admin','action'=>'toggleuser','mapid'=>$this->mapid,'id'=>$user->id),null,true ); ?>">
                    <?=($user->active)?"<i class='icon-ok icon-white'></i>":"<i class='icon-remove icon-white'></i>"?>
                    </a>    
                </td>
                <td>
                    <?=($user->role)?"Admin":"-"?>
                </td>
                <td><div class="btn-group">
                        <a class="btn btn-danger" href="/admin/deleteuser/id/<?echo $user->id;?>"><i class='icon-trash icon-white'></i>delete</a>
                        <?=$this->ajaxLink("<i class='icon-edit'></i>Modifier",
                            $this->url(array('controller' => 'admin', 'action' => 'adduser', 'id'=>$user->id)) ,
                                array('update' => '#modal .modal-body',
                                'class' => 'btn',
                                'beforeSend' => "$('#elementdetailcontent').hide('slow');$('#elementdetail').hide('slow');",
                                'complete' => "showModal()",
                            ));?>
                        <a class="btn"
                           href="<?= $this->url(array('controller'=>'admin','action'=>'toggleadmin','id'=>$user->id),null,true ); ?>">
                           <i class='icon-certificate'></i>Admin</a>
                        
                        
                        
                    </div>
                </td>

            </tr>

            <?php
            }

        ?>



        </table>
</div>

<div class="clear:both"></div>
